<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.0							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.0">
<Header n="wave.exe">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="wave.exe">
<SecHeader>
  <MetricTable>
    <Metric i="0" n="PAPI_L2_TCM.[0,0]" v="raw" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="2000000"/></Info>
    </Metric>
    <Metric i="1" n="PAPI_L1_TCM (proxy).[0,0]" v="raw" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="1"/></Info>
    </Metric>
    <Metric i="2" n="CPUTIME (usec).[0,0]" v="raw" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="1"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/home/vinicius/Documents/Projects/CAD/TP1/ex4/wave/wave.exe"/>
    <LoadModule i="180" n="&lt;unknown load module&gt;"/>
    <LoadModule i="184" n="/home/vinicius/local/hpctoolkit/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="200" n="/home/vinicius/local/hpctoolkit/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="206" n="/lib/x86_64-linux-gnu/libc-2.23.so"/>
    <LoadModule i="210" n="/lib/x86_64-linux-gnu/libpthread-2.23.so"/>
    <LoadModule i="214" n="/lib/x86_64-linux-gnu/ld-2.23.so"/>
    <LoadModule i="218" n="/home/vinicius/local/papi/lib/libpapi.so.5.4.3.0"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="./src/home/vinicius/Documents/Projects/CAD/TP1/ex4/wave/main.cc"/>
    <File i="181" n="&lt;unknown file&gt;"/>
    <File i="185" n="&lt;unknown file&gt;"/>
    <File i="201" n="&lt;unknown file&gt;"/>
    <File i="207" n="&lt;unknown file&gt;"/>
    <File i="211" n="&lt;unknown file&gt;"/>
    <File i="215" n="&lt;unknown file&gt;"/>
    <File i="219" n="./src/home/vinicius/Documents/UFRJ/CAD/papi-5.4.3/src/threads.h"/>
    <File i="222" n="&lt;unknown file&gt;"/>
    <File i="225" n="./src/home/vinicius/Documents/UFRJ/CAD/papi-5.4.3/src/components/perf_event/perf_event.c"/>
    <File i="237" n="./src/home/vinicius/Documents/UFRJ/CAD/papi-5.4.3/src/extras.c"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="4" n="Allocate3DMatrix(int, int, int)"/>
    <Procedure i="15" n="Deallocate3DMatrix(float***, Parameters*)"/>
    <Procedure i="24" n="initialize(float***, float***, float***, Parameters*)"/>
    <Procedure i="47" n="main"/>
    <Procedure i="81" n="run_wave_propagation(float***, float***, float***, float*, Parameters*)"/>
    <Procedure i="90" n="iso_3dfd_it(float***, float***, float***, float*, int, int, int)"/>
    <Procedure i="108" n="write_plane_XY(float***, Parameters*, int, char const*)"/>
    <Procedure i="182" n="&lt;partial call paths&gt;" f="1"/>
    <Procedure i="186" n="itimer_signal_handler"/>
    <Procedure i="188" n="&lt;unknown procedure&gt;"/>
    <Procedure i="190" n="hpcrun_context_pc"/>
    <Procedure i="192" n="hpcrun_trampoline_interior"/>
    <Procedure i="194" n="hpcrun_get_thread_data_local_avail"/>
    <Procedure i="196" n="papi_event_handler"/>
    <Procedure i="198" n="hpcrun_get_thread_data_local"/>
    <Procedure i="202" n="monitor_signal_handler"/>
    <Procedure i="204" n="&lt;program root&gt;" f="1"/>
    <Procedure i="208" n="&lt;unknown procedure&gt;"/>
    <Procedure i="212" n="_pthread_cleanup_pop_restore"/>
    <Procedure i="216" n="&lt;unknown procedure&gt;"/>
    <Procedure i="220" n="_papi_hwi_lookup_thread"/>
    <Procedure i="223" n="&lt;unknown procedure&gt;"/>
    <Procedure i="234" n="mmap_read_head"/>
    <Procedure i="226" n="_pe_dispatch_timer"/>
    <Procedure i="238" n="_papi_hwi_dispatch_overflow_signal"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<PF i="2" s="182" l="0" lm="180" f="181" n="182">
<C i="3" s="183" l="0">
<PF i="4" s="208" l="0" lm="206" f="207" n="208">
<C i="5" s="209" l="0">
<PF i="6" s="202" l="0" lm="200" f="201" n="202">
<C i="7" s="203" l="0">
<PF i="8" s="186" l="0" lm="184" f="185" n="186">
<C i="9" s="187" l="0">
<PF i="10" s="188" l="0" lm="184" f="185" n="188">
<S i="11" s="189" l="0">
<M n="0" v="2e+06"/><M n="1" v="916919"/>
</S>
</PF>
<PF i="12" s="216" l="0" lm="214" f="215" n="216">
<S i="13" s="217" l="0">
<M n="0" v="4e+06"/><M n="1" v="1.81416e+06"/>
</S>
</PF>
</C>
<C i="14" s="187" l="0">
<PF i="15" s="190" l="0" lm="184" f="185" n="190">
<S i="16" s="191" l="0">
<M n="0" v="2e+06"/><M n="1" v="958611"/>
</S>
</PF>
</C>
<C i="17" s="187" l="0">
<PF i="18" s="192" l="0" lm="184" f="185" n="192">
<S i="19" s="193" l="0">
<M n="0" v="4e+06"/><M n="1" v="1.79689e+06"/>
</S>
</PF>
</C>
<C i="20" s="187" l="0">
<PF i="21" s="194" l="0" lm="184" f="185" n="194">
<S i="22" s="195" l="0">
<M n="0" v="1e+07"/><M n="1" v="4.55082e+06"/>
</S>
</PF>
</C>
<S i="23" s="187" l="0">
<M n="0" v="4e+06"/><M n="1" v="1.80548e+06"/>
</S>
</PF>
</C>
<C i="24" s="203" l="0">
<PF i="25" s="220" l="102" lm="218" f="219" n="220">
<C i="26" s="221" l="102">
<PF i="27" s="216" l="0" lm="214" f="215" n="216">
<S i="28" s="217" l="0">
<M n="2" v="71602"/>
</S>
</PF>
<PF i="29" s="223" l="0" lm="218" f="222" n="223">
<S i="30" s="224" l="0">
<M n="2" v="7980"/>
</S>
</PF>
</C>
<S i="31" s="221" l="102">
<M n="2" v="7965"/>
</S>
</PF>
<PF i="32" s="226" l="1960" lm="218" f="225" n="226">
<S i="33" s="227" l="1960">
<M n="2" v="16028"/>
</S>
<S i="34" s="228" l="1967">
<M n="2" v="31920"/>
</S>
<S i="35" s="229" l="1973">
<M n="2" v="7993"/>
</S>
<S i="36" s="230" l="2003">
<M n="2" v="15972"/>
</S>
<S i="37" s="231" l="2092">
<M n="2" v="7982"/>
</S>
<C i="38" s="232" l="2016">
<PF i="39" s="208" l="0" lm="206" f="207" n="208">
<S i="40" s="209" l="0">
<M n="2" v="286522"/>
</S>
</PF>
<PF i="41" s="223" l="0" lm="218" f="222" n="223">
<S i="42" s="224" l="0">
<M n="2" v="7957"/>
</S>
</PF>
</C>
<C i="43" s="233" l="2029">
<PF i="44" s="208" l="0" lm="206" f="207" n="208">
<S i="45" s="209" l="0">
<M n="2" v="23946"/>
</S>
</PF>
<PF i="46" s="223" l="0" lm="218" f="222" n="223">
<S i="47" s="224" l="0">
<M n="2" v="15853"/>
</S>
</PF>
</C>
<C i="48" s="236" l="2081">
<PF i="49" s="238" l="223" lm="218" f="237" n="238">
<S i="50" s="239" l="223">
<M n="2" v="15843"/>
</S>
<S i="51" s="240" l="229">
<M n="2" v="7971"/>
</S>
<C i="52" s="241" l="349">
<PF i="53" s="196" l="0" lm="184" f="185" n="196">
<C i="54" s="197" l="0">
<PF i="55" s="216" l="0" lm="214" f="215" n="216">
<S i="56" s="217" l="0">
<M n="2" v="15978"/>
</S>
</PF>
</C>
<C i="57" s="197" l="0">
<PF i="58" s="192" l="0" lm="184" f="185" n="192">
<S i="59" s="193" l="0">
<M n="2" v="7996"/>
</S>
</PF>
</C>
<C i="60" s="197" l="0">
<PF i="61" s="194" l="0" lm="184" f="185" n="194">
<S i="62" s="195" l="0">
<M n="2" v="7950"/>
</S>
</PF>
</C>
<C i="63" s="197" l="0">
<PF i="64" s="198" l="0" lm="184" f="185" n="198">
<S i="65" s="199" l="0">
<M n="2" v="7955"/>
</S>
</PF>
</C>
<S i="66" s="197" l="0">
<M n="2" v="31822"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="67" s="242" l="2089">
<PF i="68" s="208" l="0" lm="206" f="207" n="208">
<S i="69" s="209" l="0">
<M n="2" v="581881"/>
</S>
</PF>
</C>
</PF>
<PF i="70" s="234" l="1790" lm="218" f="225" n="234">
<S i="71" s="235" l="1790">
<M n="2" v="7986"/>
</S>
</PF>
</C>
<S i="72" s="203" l="0">
<M n="0" v="6e+06"/><M n="1" v="2.79592e+06"/><M n="2" v="2.45078e+06"/>
</S>
</PF>
</C>
<C i="73" s="209" l="0">
<PF i="74" s="208" l="0" lm="206" f="207" n="208">
<C i="75" s="209" l="0">
<PF i="76" s="208" l="0" lm="206" f="207" n="208">
<C i="77" s="209" l="0">
<PF i="78" s="208" l="0" lm="206" f="207" n="208">
<C i="79" s="209" l="0">
<PF i="80" s="208" l="0" lm="206" f="207" n="208">
<S i="81" s="209" l="0">
<M n="2" v="63052"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
<PF i="82" s="204" l="0" lm="200" f="201" n="204">
<C i="83" s="205" l="0">
<PF i="84" s="47" l="82" lm="2" f="3" n="47">
<C i="85" s="63" l="132">
<PF i="86" s="4" l="25" lm="2" f="3" n="4">
<L i="87" s="7" l="28" f="3">
<L i="88" s="10" l="31" f="3">
<C i="89" s="12" l="32">
<PF i="90" s="208" l="0" lm="206" f="207" n="208">
<C i="91" s="209" l="0">
<PF i="92" s="208" l="0" lm="206" f="207" n="208">
<S i="93" s="209" l="0">
<M n="2" v="15625"/>
</S>
</PF>
</C>
</PF>
</C>
</L>
</L>
</PF>
</C>
<C i="94" s="64" l="133">
<PF i="95" s="4" l="25" lm="2" f="3" n="4">
<L i="96" s="7" l="28" f="3">
<L i="97" s="10" l="31" f="3">
<C i="98" s="12" l="32">
<PF i="99" s="208" l="0" lm="206" f="207" n="208">
<C i="100" s="209" l="0">
<PF i="101" s="208" l="0" lm="206" f="207" n="208">
<S i="102" s="209" l="0">
<M n="2" v="23917"/>
</S>
</PF>
</C>
</PF>
</C>
</L>
</L>
</PF>
</C>
<C i="103" s="65" l="134">
<PF i="104" s="4" l="25" lm="2" f="3" n="4">
<L i="105" s="7" l="28" f="3">
<L i="106" s="10" l="31" f="3">
<S i="107" s="11" l="31">
<M n="2" v="7972"/>
</S>
<C i="108" s="12" l="32">
<PF i="109" s="208" l="0" lm="206" f="207" n="208">
<C i="110" s="209" l="0">
<PF i="111" s="208" l="0" lm="206" f="207" n="208">
<S i="112" s="209" l="0">
<M n="2" v="7990"/>
</S>
</PF>
</C>
</PF>
</C>
</L>
</L>
</PF>
</C>
<C i="113" s="71" l="143">
<PF i="114" s="24" l="55" lm="2" f="3" n="24">
<L i="115" s="26" l="57" f="3">
<L i="116" s="28" l="58" f="3">
<L i="117" s="30" l="59" f="3">
<S i="118" s="31" l="59">
<M n="0" v="2.8e+07"/><M n="1" v="2.67647e+07"/><M n="2" v="199370"/>
</S>
<S i="119" s="32" l="60">
<M n="0" v="2.2e+07"/><M n="1" v="2.03996e+07"/><M n="2" v="223760"/>
</S>
<S i="120" s="33" l="61">
<M n="0" v="5e+07"/><M n="1" v="4.81461e+07"/><M n="2" v="646570"/>
</S>
<S i="121" s="34" l="62">
<M n="0" v="6.2e+07"/><M n="1" v="5.78423e+07"/><M n="2" v="518273"/>
</S>
</L>
</L>
</L>
</PF>
</C>
<C i="122" s="72" l="146">
<PF i="123" s="108" l="209" lm="2" f="3" n="108">
<L i="124" s="113" l="218" f="3">
<L i="125" s="115" l="219" f="3">
<C i="126" s="117" l="220">
<PF i="127" s="208" l="0" lm="206" f="207" n="208">
<C i="128" s="209" l="0">
<PF i="129" s="208" l="0" lm="206" f="207" n="208">
<C i="130" s="209" l="0">
<PF i="131" s="208" l="0" lm="206" f="207" n="208">
<S i="132" s="209" l="0">
<M n="2" v="7996"/>
</S>
</PF>
</C>
<C i="133" s="209" l="0">
<PF i="134" s="208" l="0" lm="206" f="207" n="208">
<C i="135" s="209" l="0">
<PF i="136" s="208" l="0" lm="206" f="207" n="208">
<S i="137" s="209" l="0">
<M n="2" v="31904"/>
</S>
</PF>
</C>
<S i="138" s="209" l="0">
<M n="2" v="13238"/>
</S>
</PF>
</C>
<S i="139" s="209" l="0">
<M n="2" v="15990"/>
</S>
</PF>
</C>
</PF>
</C>
<S i="140" s="117" l="220">
<M n="2" v="15980"/>
</S>
</L>
</L>
</PF>
</C>
<C i="141" s="74" l="150">
<PF i="142" s="81" l="163" lm="2" f="3" n="81">
<L i="143" s="83" l="168" f="3">
<C i="144" s="85" l="170">
<PF i="145" s="90" l="184" lm="2" f="3" n="90">
<L i="146" s="92" l="186" f="3">
<L i="147" s="94" l="187" f="3">
<S i="148" s="95" l="187">
<M n="2" v="7997"/>
</S>
<L i="149" s="96" l="188" f="3">
<S i="150" s="97" l="188">
<M n="0" v="8.6e+07"/><M n="1" v="3.95915e+07"/><M n="2" v="1.71642e+06"/>
</S>
<S i="151" s="98" l="191">
<M n="0" v="8.2e+07"/><M n="1" v="3.80301e+07"/><M n="2" v="2.29104e+06"/>
</S>
<S i="152" s="99" l="194">
<M n="0" v="1.4e+07"/><M n="1" v="6.52157e+06"/><M n="2" v="367290"/>
</S>
<S i="153" s="100" l="195">
<M n="0" v="6.22e+08"/><M n="1" v="2.90205e+08"/><M n="2" v="1.47474e+07"/>
</S>
<L i="154" s="101" l="196" f="3">
<S i="155" s="102" l="196">
<M n="0" v="2.1e+09"/><M n="1" v="9.67363e+08"/><M n="2" v="7.74952e+06"/>
</S>
<S i="156" s="103" l="197">
<M n="0" v="3.4226e+10"/><M n="1" v="1.57981e+10"/><M n="2" v="2.04262e+08"/>
</S>
<S i="157" s="104" l="198">
<M n="0" v="2.8912e+10"/><M n="1" v="1.34178e+10"/><M n="2" v="2.71705e+08"/>
</S>
<S i="158" s="105" l="199">
<M n="0" v="2.6612e+10"/><M n="1" v="1.23096e+10"/><M n="2" v="1.2387e+08"/>
</S>
</L>
<S i="159" s="106" l="201">
<M n="0" v="2.2722e+10"/><M n="1" v="1.05088e+10"/><M n="2" v="2.2857e+08"/>
</S>
</L>
</L>
</L>
</PF>
</C>
<C i="160" s="86" l="173">
<PF i="161" s="90" l="184" lm="2" f="3" n="90">
<L i="162" s="92" l="186" f="3">
<L i="163" s="94" l="187" f="3">
<S i="164" s="95" l="187">
<M n="0" v="2e+06"/><M n="1" v="899322"/><M n="2" v="15842"/>
</S>
<L i="165" s="96" l="188" f="3">
<S i="166" s="97" l="188">
<M n="0" v="6.4e+07"/><M n="1" v="2.95413e+07"/><M n="2" v="1.61227e+06"/>
</S>
<S i="167" s="98" l="191">
<M n="0" v="7.4e+07"/><M n="1" v="3.43329e+07"/><M n="2" v="2.18736e+06"/>
</S>
<S i="168" s="99" l="194">
<M n="0" v="1.4e+07"/><M n="1" v="6.31723e+06"/><M n="2" v="447219"/>
</S>
<S i="169" s="100" l="195">
<M n="0" v="2.78e+08"/><M n="1" v="1.29599e+08"/><M n="2" v="7.96694e+06"/>
</S>
<L i="170" s="101" l="196" f="3">
<S i="171" s="102" l="196">
<M n="0" v="2.234e+09"/><M n="1" v="1.02677e+09"/><M n="2" v="7.57445e+06"/>
</S>
<S i="172" s="103" l="197">
<M n="0" v="3.2986e+10"/><M n="1" v="1.52034e+10"/><M n="2" v="2.07893e+08"/>
</S>
<S i="173" s="104" l="198">
<M n="0" v="2.9602e+10"/><M n="1" v="1.37008e+10"/><M n="2" v="2.69021e+08"/>
</S>
<S i="174" s="105" l="199">
<M n="0" v="2.7424e+10"/><M n="1" v="1.26401e+10"/><M n="2" v="1.26022e+08"/>
</S>
</L>
<S i="175" s="106" l="201">
<M n="0" v="2.2778e+10"/><M n="1" v="1.05025e+10"/><M n="2" v="2.30588e+08"/>
</S>
</L>
</L>
</L>
</PF>
</C>
<C i="176" s="88" l="177">
<PF i="177" s="108" l="209" lm="2" f="3" n="108">
<L i="178" s="113" l="218" f="3">
<L i="179" s="115" l="219" f="3">
<C i="180" s="117" l="220">
<PF i="181" s="208" l="0" lm="206" f="207" n="208">
<C i="182" s="209" l="0">
<PF i="183" s="208" l="0" lm="206" f="207" n="208">
<C i="184" s="209" l="0">
<PF i="185" s="212" l="0" lm="210" f="211" n="212">
<S i="186" s="213" l="0">
<M n="2" v="8002"/>
</S>
</PF>
</C>
<C i="187" s="209" l="0">
<PF i="188" s="208" l="0" lm="206" f="207" n="208">
<S i="189" s="209" l="0">
<M n="2" v="15773"/>
</S>
</PF>
</C>
<C i="190" s="209" l="0">
<PF i="191" s="208" l="0" lm="206" f="207" n="208">
<C i="192" s="209" l="0">
<PF i="193" s="208" l="0" lm="206" f="207" n="208">
<S i="194" s="209" l="0">
<M n="0" v="2e+06"/><M n="1" v="1.07895e+06"/><M n="2" v="7990"/>
</S>
</PF>
</C>
<C i="195" s="209" l="0">
<PF i="196" s="208" l="0" lm="206" f="207" n="208">
<C i="197" s="209" l="0">
<PF i="198" s="208" l="0" lm="206" f="207" n="208">
<C i="199" s="209" l="0">
<PF i="200" s="208" l="0" lm="206" f="207" n="208">
<S i="201" s="209" l="0">
<M n="2" v="8010"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<S i="202" s="209" l="0">
<M n="2" v="23981"/>
</S>
</PF>
</C>
<C i="203" s="209" l="0">
<PF i="204" s="208" l="0" lm="206" f="207" n="208">
<C i="205" s="209" l="0">
<PF i="206" s="208" l="0" lm="206" f="207" n="208">
<S i="207" s="209" l="0">
<M n="0" v="2e+06"/><M n="1" v="918207"/><M n="2" v="7863"/>
</S>
</PF>
</C>
<C i="208" s="209" l="0">
<PF i="209" s="208" l="0" lm="206" f="207" n="208">
<C i="210" s="209" l="0">
<PF i="211" s="208" l="0" lm="206" f="207" n="208">
<S i="212" s="209" l="0">
<M n="2" v="183613"/>
</S>
</PF>
</C>
<S i="213" s="209" l="0">
<M n="2" v="111380"/>
</S>
</PF>
</C>
<C i="214" s="209" l="0">
<PF i="215" s="208" l="0" lm="206" f="207" n="208">
<S i="216" s="209" l="0">
<M n="2" v="24001"/>
</S>
</PF>
</C>
<C i="217" s="209" l="0">
<PF i="218" s="208" l="0" lm="206" f="207" n="208">
<C i="219" s="209" l="0">
<PF i="220" s="208" l="0" lm="206" f="207" n="208">
<S i="221" s="209" l="0">
<M n="2" v="16002"/>
</S>
</PF>
</C>
<S i="222" s="209" l="0">
<M n="2" v="7973"/>
</S>
</PF>
</C>
<C i="223" s="209" l="0">
<PF i="224" s="208" l="0" lm="206" f="207" n="208">
<S i="225" s="209" l="0">
<M n="2" v="95383"/>
</S>
</PF>
</C>
<C i="226" s="209" l="0">
<PF i="227" s="208" l="0" lm="206" f="207" n="208">
<S i="228" s="209" l="0">
<M n="2" v="31451"/>
</S>
</PF>
</C>
<C i="229" s="209" l="0">
<PF i="230" s="208" l="0" lm="206" f="207" n="208">
<C i="231" s="209" l="0">
<PF i="232" s="208" l="0" lm="206" f="207" n="208">
<S i="233" s="209" l="0">
<M n="2" v="15969"/>
</S>
</PF>
</C>
<S i="234" s="209" l="0">
<M n="2" v="31865"/>
</S>
</PF>
</C>
<C i="235" s="209" l="0">
<PF i="236" s="208" l="0" lm="206" f="207" n="208">
<S i="237" s="209" l="0">
<M n="2" v="15958"/>
</S>
</PF>
</C>
<C i="238" s="209" l="0">
<PF i="239" s="208" l="0" lm="206" f="207" n="208">
<S i="240" s="209" l="0">
<M n="2" v="23817"/>
</S>
</PF>
</C>
<C i="241" s="209" l="0">
<PF i="242" s="208" l="0" lm="206" f="207" n="208">
<S i="243" s="209" l="0">
<M n="2" v="79746"/>
</S>
</PF>
</C>
<C i="244" s="209" l="0">
<PF i="245" s="208" l="0" lm="206" f="207" n="208">
<S i="246" s="209" l="0">
<M n="2" v="8016"/>
</S>
</PF>
</C>
<C i="247" s="209" l="0">
<PF i="248" s="208" l="0" lm="206" f="207" n="208">
<S i="249" s="209" l="0">
<M n="2" v="7996"/>
</S>
</PF>
</C>
<C i="250" s="209" l="0">
<PF i="251" s="208" l="0" lm="206" f="207" n="208">
<S i="252" s="209" l="0">
<M n="2" v="7996"/>
</S>
</PF>
</C>
<C i="253" s="209" l="0">
<PF i="254" s="208" l="0" lm="206" f="207" n="208">
<S i="255" s="209" l="0">
<M n="2" v="15994"/>
</S>
</PF>
</C>
<S i="256" s="209" l="0">
<M n="2" v="733164"/>
</S>
</PF>
</C>
<C i="257" s="209" l="0">
<PF i="258" s="208" l="0" lm="206" f="207" n="208">
<S i="259" s="209" l="0">
<M n="2" v="8015"/>
</S>
</PF>
</C>
<S i="260" s="209" l="0">
<M n="2" v="159714"/>
</S>
</PF>
</C>
</PF>
</C>
<S i="261" s="117" l="220">
<M n="0" v="2e+06"/><M n="1" v="1.28223e+06"/><M n="2" v="207532"/>
</S>
</L>
</L>
</PF>
</C>
</L>
</PF>
</C>
<C i="262" s="76" l="154">
<PF i="263" s="15" l="40" lm="2" f="3" n="15">
<L i="264" s="17" l="42" f="3">
<L i="265" s="19" l="44" f="3">
<C i="266" s="21" l="45">
<PF i="267" s="208" l="0" lm="206" f="207" n="208">
<C i="268" s="209" l="0">
<PF i="269" s="208" l="0" lm="206" f="207" n="208">
<S i="270" s="209" l="0">
<M n="0" v="2e+06"/><M n="1" v="904474"/><M n="2" v="7998"/>
</S>
</PF>
</C>
</PF>
</C>
</L>
</L>
</PF>
</C>
<C i="271" s="78" l="156">
<PF i="272" s="15" l="40" lm="2" f="3" n="15">
<L i="273" s="17" l="42" f="3">
<L i="274" s="19" l="44" f="3">
<C i="275" s="21" l="45">
<PF i="276" s="208" l="0" lm="206" f="207" n="208">
<C i="277" s="209" l="0">
<PF i="278" s="208" l="0" lm="206" f="207" n="208">
<S i="279" s="209" l="0">
<M n="2" v="7985"/>
</S>
</PF>
</C>
</PF>
</C>
</L>
</L>
</PF>
</C>
</PF>
</C>
</PF>
</SecCallPathProfileData>
</SecCallPathProfile>
</HPCToolkitExperiment>
